# Generated by Django 5.2.17 on 2026-09-02 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblifyruser',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='joblifyruser',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='joblifyruser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
