# Generated by Django 5.2.17 on 2026-08-31 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('work_mode', models.CharField(default='Remote', max_length=50)),
                ('pay_range', models.CharField(max_length=100)),
                ('pay_full', models.CharField(blank=True, max_length=100)),
                ('job_type', models.CharField(default='Full-time', max_length=50)),
                ('description', models.TextField()),
                ('full_description', models.TextField(blank=True)),
                ('responsibilities', models.JSONField(default=list)),
                ('logo_text', models.CharField(blank=True, max_length=10)),
                ('logo_bg', models.CharField(blank=True, max_length=100)),
                ('match_score', models.CharField(blank=True, max_length=20, null=True)),
                ('posted_label', models.CharField(default='Posted recently', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.IntegerField(default=95)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
